---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project
  labels:
    app: capstone-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-project
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-project
    spec:
      containers:
        - image: arnoldrx/capstone-project:latest
          name: capstone-project
          ports:
            - containerPort: 3000
              name: nodejs-server
          livenessProbe:
            httpGet:
              path: /
              scheme: HTTP
              port: 3000
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-project
  labels:
    name: capstone-project
spec:
  selector:
    app: capstone-project
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443

